Add input error handling and remove unnecessary vars
Change-Id: Ided376e5e1256675a571ccbbdff1f266d3f802ad

diff --git a/bootstrap/create-cluster.yaml b/bootstrap/create-cluster.yaml
--- a/bootstrap/create-cluster.yaml
+++ b/bootstrap/create-cluster.yaml
@@ -5,6 +5,7 @@ steps:
   script: |
     #!/usr/bin/env bash
     set +x
+    set -o pipefail
 
     HARDWARE_MANAGMENT_API_ENDPOINT="https://gdchardwaremanagement.googleapis.com"
     if [[ -n "${HARDWARE_MANAGMENT_API_ENDPOINT_OVERRIDE}" ]]; then
@@ -44,9 +45,33 @@ steps:
 
     }
 
-    [[ -z "${STORE_ID}" ]] && die "STORE_ID not set"
+    function parse_csv_required() {
+      input="$1"
+      column="$2"
 
-    NODE_LOCATION=${ZONE}
+      output=$(echo "$input" | csvtool namedcol "$column" - | csvtool drop 1 -)
+
+      [[ $? -ne 0 ]] && die "Missing required parameter $2"
+
+      if [ -z "$output" ]; then
+        die "Empty required parameter $2"
+      fi
+
+      echo "$output"
+    }
+
+    function parse_csv_optional() {
+      input="$1"
+      column="$2"
+
+      output=$(echo "$input" | csvtool namedcol "$column" - | csvtool drop 1 -)
+
+      echo "$output"
+    }
+
+    [[ -z "${_STORE_ID}" ]] && die "STORE_ID not set"
+
+    NODE_LOCATION=${_ZONE}
     [[ -z "$NODE_LOCATION" ]] && die "ZONE not set"
 
     apt-get update
@@ -56,33 +81,33 @@ steps:
     git clone -b $SOURCE_OF_TRUTH_BRANCH https://oauth2:$TOKEN@$SOURCE_OF_TRUTH_REPO repo
     cp repo/$SOURCE_OF_TRUTH_PATH ./cluster-intent-registry.csv
 
-    export CLUSTER_INTENT_ROW=$(awk -F , "\$1 == \"$STORE_ID\" || \$1 == \"\\\"$STORE_ID\\\"\"" cluster-intent-registry.csv)
+    export CLUSTER_INTENT_ROW=$(awk -F , "\$1 == \"$_STORE_ID\" || \$1 == \"\\\"$_STORE_ID\\\"\"" cluster-intent-registry.csv)
     echo $CLUSTER_INTENT_ROW
-    [[ -z "$CLUSTER_INTENT_ROW" ]] && die "Cluster intent not found for store $STORE_ID"
+    [[ -z "$CLUSTER_INTENT_ROW" ]] && die "Cluster intent not found for store $_STORE_ID"
     export CLUSTER_INTENT_HEADER=$(head -1 cluster-intent-registry.csv)
     export CLUSTER_INTENT="$CLUSTER_INTENT_HEADER"$'\n'"$CLUSTER_INTENT_ROW"
 
 
     # Set parameters from cluster intent
-    export MACHINE_PROJECT_ID=$(echo "$CLUSTER_INTENT" | csvtool namedcol "machine_project_id" - | csvtool drop 1 -)
-    export FLEET_PROJECT_ID=$(echo "$CLUSTER_INTENT" | csvtool namedcol "fleet_project_id" - | csvtool drop 1 -)
-    export CLUSTER_NAME=$(echo "$CLUSTER_INTENT" | csvtool namedcol "cluster_name" - | csvtool drop 1 -)
-    export LOCATION=$(echo "$CLUSTER_INTENT" | csvtool namedcol "location" - | csvtool drop 1 -)
-    export NODE_COUNT=$(echo "$CLUSTER_INTENT" | csvtool namedcol "node_count" - | csvtool drop 1 -)
-    export CLUSTER_IPV4_CIDR=$(echo "$CLUSTER_INTENT" | csvtool namedcol "cluster_ipv4_cidr" - | csvtool drop 1 -)
-    export SERVICES_IPV4_CIDR=$(echo "$CLUSTER_INTENT" | csvtool namedcol "services_ipv4_cidr" - | csvtool drop 1 -)
-    export EXTERNAL_LOAD_BALANCER_IPV4_ADDRESS_POOLS=$(echo "$CLUSTER_INTENT" | csvtool namedcol "external_load_balancer_ipv4_address_pools" - | csvtool drop 1 -)
-    export SYNC_REPO=$(echo "$CLUSTER_INTENT" | csvtool namedcol "sync_repo" - | csvtool drop 1 -)
-    export SYNC_BRANCH=$(echo "$CLUSTER_INTENT" | csvtool namedcol "sync_branch" - | csvtool drop 1 -)
-    export SYNC_DIR=$(echo "$CLUSTER_INTENT" | csvtool namedcol "sync_dir" - | csvtool drop 1 -)
-    export SECRETS_PROJECT_ID=$(echo "$CLUSTER_INTENT" | csvtool namedcol "secrets_project_id" - | csvtool drop 1 -)
-    export GIT_TOKEN_SECRETS_MANAGER_NAME=$(echo "$CLUSTER_INTENT" | csvtool namedcol "git_token_secrets_manager_name" - | csvtool drop 1 -)
-    export CLUSTER_VERSION=$(echo "$CLUSTER_INTENT" | csvtool namedcol "cluster_version" - | csvtool drop 1 -)
-    export MAINTENANCE_WINDOW_START=$(echo "$CLUSTER_INTENT" | csvtool namedcol "maintenance_window_start" - | csvtool drop 1 -)
-    export MAINTENANCE_WINDOW_END=$(echo "$CLUSTER_INTENT" | csvtool namedcol "maintenance_window_end" - | csvtool drop 1 -)
-    export MAINTENANCE_WINDOW_RECURRENCE=$(echo "$CLUSTER_INTENT" | csvtool namedcol "maintenance_window_recurrence" - | csvtool drop 1 -)
-    export SUBNET_VLANS=$(echo "$CLUSTER_INTENT" | csvtool namedcol "subnet_vlans" - | csvtool drop 1 - | tr -d '"')
-    export ZONE_NAME_FROM_SOT=$(echo "$CLUSTER_INTENT" | csvtool namedcol "zone_name" - | csvtool drop 1 -)
+    export MACHINE_PROJECT_ID=$(parse_csv_required "$CLUSTER_INTENT" "machine_project_id")
+    export FLEET_PROJECT_ID=$(parse_csv_required "$CLUSTER_INTENT" "fleet_project_id")
+    export CLUSTER_NAME=$(parse_csv_required "$CLUSTER_INTENT" "cluster_name")
+    export LOCATION=$(parse_csv_required "$CLUSTER_INTENT" "location")
+    export NODE_COUNT=$(parse_csv_required "$CLUSTER_INTENT" "node_count")
+    export CLUSTER_IPV4_CIDR=$(parse_csv_required "$CLUSTER_INTENT" "cluster_ipv4_cidr")
+    export SERVICES_IPV4_CIDR=$(parse_csv_required "$CLUSTER_INTENT" "services_ipv4_cidr")
+    export EXTERNAL_LOAD_BALANCER_IPV4_ADDRESS_POOLS=$(parse_csv_required "$CLUSTER_INTENT" "external_load_balancer_ipv4_address_pools")
+    export SYNC_REPO=$(parse_csv_required "$CLUSTER_INTENT" "sync_repo")
+    export SYNC_BRANCH=$(parse_csv_required "$CLUSTER_INTENT" "sync_branch")
+    export SYNC_DIR=$(parse_csv_required "$CLUSTER_INTENT" "sync_dir")
+    export SECRETS_PROJECT_ID=$(parse_csv_required "$CLUSTER_INTENT" "secrets_project_id")
+    export GIT_TOKEN_SECRETS_MANAGER_NAME=$(parse_csv_required "$CLUSTER_INTENT" "git_token_secrets_manager_name")
+    export CLUSTER_VERSION=$(parse_csv_required "$CLUSTER_INTENT" "cluster_version")
+    export MAINTENANCE_WINDOW_START=$(parse_csv_optional "$CLUSTER_INTENT" "maintenance_window_start")
+    export MAINTENANCE_WINDOW_END=$(parse_csv_optional "$CLUSTER_INTENT" "maintenance_window_end")
+    export MAINTENANCE_WINDOW_RECURRENCE=$(parse_csv_optional "$CLUSTER_INTENT" "maintenance_window_recurrence")
+    export SUBNET_VLANS=$(parse_csv_optional "$CLUSTER_INTENT" "subnet_vlans" | tr -d '"')
+    export ZONE_NAME_FROM_SOT=$(parse_csv_optional "$CLUSTER_INTENT" "zone_name")
 
     if [ -n "${EDGE_CONTAINER_API_ENDPOINT_OVERRIDE:-}" ]; then
       echo "Setting api_endpoint_overrides/edgecontainer to $EDGE_CONTAINER_API_ENDPOINT_OVERRIDE"
@@ -165,6 +190,9 @@ steps:
       fi
     done
 
+    set -eE
+    trap 'die "Error configuring cluster"' ERR
+
     export KUBECONFIG="$(pwd)/gateway-kubeconfig"
     gcloud container fleet memberships get-credentials $CLUSTER_NAME --project $FLEET_PROJECT_ID
 
@@ -185,10 +213,12 @@ steps:
     gcloud beta container fleet config-management apply --membership=$CLUSTER_NAME \
         --config=./apply-spec.yaml --project $FLEET_PROJECT_ID
 
-    gcloud container fleet identity-service enable --project $FLEET_PROJECT_ID
+    if [ -z "${SKIP_IDENTITY_SERVICE}" ]; then
+      gcloud container fleet identity-service apply --membership=$CLUSTER_NAME \
+          --config=./auth-config.yaml --project $FLEET_PROJECT_ID
+    fi
 
-    gcloud container fleet identity-service apply --membership=$CLUSTER_NAME \
-        --config=./auth-config.yaml --project $FLEET_PROJECT_ID
+    set +e
 
     if [ -z "${SKIP_HEALTH_CHECK}" ]; then
       count=0
@@ -211,8 +241,10 @@ steps:
     if [[ -n "${ZONE_NAME_FROM_SOT}" ]]; then
       echo "Zone name is defined in SOT... skipping zone signal completion."
     else
-      zone_signal_complete "projects/${MACHINE_PROJECT_ID}/locations/${LOCATION}/zones/${STORE_ID}"
+      zone_signal_complete "projects/${MACHINE_PROJECT_ID}/locations/${LOCATION}/zones/${_STORE_ID}"
     fi
+
+    set -eE
 
     export VIRTCTL_VERSION=v1.2.2
     curl -L https://github.com/kubevirt/kubevirt/releases/download/${VIRTCTL_VERSION}/virtctl-${VIRTCTL_VERSION}-linux-amd64 -o virtctl
@@ -228,8 +260,6 @@ steps:
     echo "Cluster Creation Succeeded: $CLUSTER_NAME"
 
   env:
-  - 'STORE_ID=$_STORE_ID'
-  - 'ZONE=$_ZONE'
   - 'EDGE_CONTAINER_API_ENDPOINT_OVERRIDE=$_EDGE_CONTAINER_API_ENDPOINT_OVERRIDE'
   - 'EDGE_NETWORK_API_ENDPOINT_OVERRIDE=$_EDGE_NETWORK_API_ENDPOINT_OVERRIDE'
   - 'GKEHUB_API_ENDPOINT_OVERRIDE=$_GKEHUB_API_ENDPOINT_OVERRIDE'
@@ -240,6 +270,8 @@ steps:
   - 'SOURCE_OF_TRUTH_PATH=$_SOURCE_OF_TRUTH_PATH'
   - 'GIT_SECRET_ID=$_GIT_SECRET_ID'
   - 'GIT_SECRETS_PROJECT_ID=$_GIT_SECRETS_PROJECT_ID'
+  - 'SKIP_HEALTH_CHECK=$_SKIP_HEALTH_CHECK'
+  - 'SKIP_IDENTITY_SERVICE=$_SKIP_IDENTITY_SERVICE'
 timeout: 14400s
 options:
   logging: CLOUD_LOGGING_ONLY
diff --git a/bootstrap/modify-cluster.yaml b/bootstrap/modify-cluster.yaml
--- a/bootstrap/modify-cluster.yaml
+++ b/bootstrap/modify-cluster.yaml
@@ -5,15 +5,40 @@ steps:
   script: |
     #!/usr/bin/env bash
     set +x
+    set -o pipefail
 
     function die() {
       echo "Cluster Modify Failed: $1"
       exit 1
     }
 
-    [[ -z "${STORE_ID}" ]] && die "STORE_ID not set"
+    function parse_csv_required() {
+      input="$1"
+      column="$2"
 
-    NODE_LOCATION=${ZONE}
+      output=$(echo "$input" | csvtool namedcol "$column" - | csvtool drop 1 -)
+
+      [[ $? -ne 0 ]] && die "Missing required parameter $2"
+
+      if [ -z "$output" ]; then
+        die "Empty required parameter $2"
+      fi
+
+      echo "$output"
+    }
+
+    function parse_csv_optional() {
+      input="$1"
+      column="$2"
+
+      output=$(echo "$input" | csvtool namedcol "$column" - | csvtool drop 1 -)
+
+      echo "$output"
+    }
+
+    [[ -z "${_STORE_ID}" ]] && die "STORE_ID not set"
+
+    NODE_LOCATION=${_ZONE}
     [[ -z "$NODE_LOCATION" ]] && die "ZONE not set"
 
     apt-get update
@@ -27,22 +52,22 @@ steps:
 
     cp repo/$SOURCE_OF_TRUTH_PATH ./cluster-intent-registry.csv
 
-    export CLUSTER_INTENT_ROW=$(awk -F , "\$1 == \"$STORE_ID\" || \$1 == \"\\\"$STORE_ID\\\"\"" cluster-intent-registry.csv)
+    export CLUSTER_INTENT_ROW=$(awk -F , "\$1 == \"$_STORE_ID\" || \$1 == \"\\\"$_STORE_ID\\\"\"" cluster-intent-registry.csv)
     echo $CLUSTER_INTENT_ROW
-    [[ -z "${CLUSTER_INTENT_ROW}" ]] && die "Cluster intent not found for store ${STORE_ID}"
+    [[ -z "${CLUSTER_INTENT_ROW}" ]] && die "Cluster intent not found for store ${_STORE_ID}"
 
     export CLUSTER_INTENT_HEADER=$(head -1 cluster-intent-registry.csv)
     export CLUSTER_INTENT="$CLUSTER_INTENT_HEADER"$'\n'"$CLUSTER_INTENT_ROW"
 
     # Set parameters from cluster intent
-    export MACHINE_PROJECT_ID=$(echo "$CLUSTER_INTENT" | csvtool namedcol "machine_project_id" - | csvtool drop 1 -)
-    export FLEET_PROJECT_ID=$(echo "$CLUSTER_INTENT" | csvtool namedcol "fleet_project_id" - | csvtool drop 1 -)
-    export CLUSTER_NAME=$(echo "$CLUSTER_INTENT" | csvtool namedcol "cluster_name" - | csvtool drop 1 -)
-    export LOCATION=$(echo "$CLUSTER_INTENT" | csvtool namedcol "location" - | csvtool drop 1 -)
-    export MAINTENANCE_WINDOW_START=$(echo "$CLUSTER_INTENT" | csvtool namedcol "maintenance_window_start" - | csvtool drop 1 -)
-    export MAINTENANCE_WINDOW_END=$(echo "$CLUSTER_INTENT" | csvtool namedcol "maintenance_window_end" - | csvtool drop 1 -)
-    export MAINTENANCE_WINDOW_RECURRENCE=$(echo "$CLUSTER_INTENT" | csvtool namedcol "maintenance_window_recurrence" - | csvtool drop 1 -)
-    export SUBNET_VLANS=$(echo "$CLUSTER_INTENT" | csvtool namedcol "subnet_vlans" - | csvtool drop 1 - | tr -d '"')
+    export MACHINE_PROJECT_ID=$(parse_csv_required "$CLUSTER_INTENT" "machine_project_id")
+    export FLEET_PROJECT_ID=$(parse_csv_required "$CLUSTER_INTENT" "fleet_project_id")
+    export CLUSTER_NAME=$(parse_csv_required "$CLUSTER_INTENT" "cluster_name")
+    export LOCATION=$(parse_csv_required "$CLUSTER_INTENT" "location")
+    export MAINTENANCE_WINDOW_START=$(parse_csv_optional "$CLUSTER_INTENT" "maintenance_window_start")
+    export MAINTENANCE_WINDOW_END=$(parse_csv_optional "$CLUSTER_INTENT" "maintenance_window_end")
+    export MAINTENANCE_WINDOW_RECURRENCE=$(parse_csv_optional "$CLUSTER_INTENT" "maintenance_window_recurrence")
+    export SUBNET_VLANS=$(parse_csv_optional "$CLUSTER_INTENT" "subnet_vlans" | tr -d '"')
 
     if [ -n "${EDGE_CONTAINER_API_ENDPOINT_OVERRIDE:-}" ]; then
       echo "Setting api_endpoint_overrides/edgecontainer to $EDGE_CONTAINER_API_ENDPOINT_OVERRIDE"
@@ -98,8 +123,6 @@ steps:
     echo "Cluster Modify Succeeded: Completed reconciling $NODE_LOCATION"
 
   env:
-  - 'STORE_ID=$_STORE_ID'
-  - 'ZONE=$_ZONE'
   - 'EDGE_CONTAINER_API_ENDPOINT_OVERRIDE=$_EDGE_CONTAINER_API_ENDPOINT_OVERRIDE'
   - 'EDGE_NETWORK_API_ENDPOINT_OVERRIDE=$_EDGE_NETWORK_API_ENDPOINT_OVERRIDE'
   - 'GKEHUB_API_ENDPOINT_OVERRIDE=$_GKEHUB_API_ENDPOINT_OVERRIDE'
